// Trading universe (CONCEPT.md §2): NIFTY 100 constituents + ETF whitelist.
// Constituents snapshot from nsearchives ind_nifty100list.csv on 2026-08-31;
// refresh quarterly (index reconstitutions) — a stale entry self-corrects:
// orders in delisted names reject at fill time for lack of price data.

export const NIFTY100 = [
  "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "AMBUJACEM", "APOLLOHOSP",
  "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE", "BANKBARODA", "BEL",
  "BHARTIARTL", "BOSCHLTD", "BPCL", "BRITANNIA", "CANBK", "CGPOWER", "CHOLAFIN", "CIPLA",
  "COALINDIA", "CUMMINSIND", "DIVISLAB", "DLF", "DMART", "DRREDDY", "EICHERMOT", "ENRIN",
  "ETERNAL", "GAIL", "GODREJCP", "GRASIM", "HAL", "HCLTECH", "HDFCAMC", "HDFCBANK",
  "HDFCLIFE", "HINDALCO", "HINDUNILVR", "HINDZINC", "HYUNDAI", "ICICIBANK", "INDHOTEL", "INDIGO",
  "INFY", "IOC", "IRFC", "ITC", "JINDALSTEL", "JIOFIN", "JSWSTEEL", "KOTAKBANK",
  "LODHA", "LT", "LTM", "M&M", "MARUTI", "MAXHEALTH", "MAZDOCK", "MOTHERSON",
  "MUTHOOTFIN", "NESTLEIND", "NTPC", "ONGC", "PFC", "PIDILITIND", "PNB", "POWERGRID",
  "RECLTD", "RELIANCE", "SBILIFE", "SBIN", "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SOLARINDS",
  "SUNPHARMA", "TATACAP", "TATACONSUM", "TATAPOWER", "TATASTEEL", "TCS", "TECHM", "TITAN",
  "TMCV", "TMPV", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO", "UNIONBANK", "UNITDSPR",
  "VBL", "VEDL", "WIPRO", "ZYDUSLIFE",
] as const;

/** Industry per constituent (from the same NSE list) — drives the sector heatmap. */
export const SECTOR_OF: Record<string, string> = {
  "ABB": "Capital Goods",
  "ADANIENSOL": "Power",
  "ADANIENT": "Metals & Mining",
  "ADANIGREEN": "Power",
  "ADANIPORTS": "Services",
  "ADANIPOWER": "Power",
  "AMBUJACEM": "Construction Materials",
  "APOLLOHOSP": "Healthcare",
  "ASIANPAINT": "Consumer Durables",
  "AXISBANK": "Financial Services",
  "BAJAJ-AUTO": "Automobile and Auto Components",
  "BAJAJFINSV": "Financial Services",
  "BAJAJHLDNG": "Financial Services",
  "BAJFINANCE": "Financial Services",
  "BANKBARODA": "Financial Services",
  "BEL": "Capital Goods",
  "BHARTIARTL": "Telecommunication",
  "BOSCHLTD": "Automobile and Auto Components",
  "BPCL": "Oil Gas & Consumable Fuels",
  "BRITANNIA": "Fast Moving Consumer Goods",
  "CANBK": "Financial Services",
  "CGPOWER": "Capital Goods",
  "CHOLAFIN": "Financial Services",
  "CIPLA": "Healthcare",
  "COALINDIA": "Oil Gas & Consumable Fuels",
  "CUMMINSIND": "Capital Goods",
  "DIVISLAB": "Healthcare",
  "DLF": "Realty",
  "DMART": "Consumer Services",
  "DRREDDY": "Healthcare",
  "EICHERMOT": "Automobile and Auto Components",
  "ENRIN": "Capital Goods",
  "ETERNAL": "Consumer Services",
  "GAIL": "Oil Gas & Consumable Fuels",
  "GODREJCP": "Fast Moving Consumer Goods",
  "GRASIM": "Construction Materials",
  "HAL": "Capital Goods",
  "HCLTECH": "Information Technology",
  "HDFCAMC": "Financial Services",
  "HDFCBANK": "Financial Services",
  "HDFCLIFE": "Financial Services",
  "HINDALCO": "Metals & Mining",
  "HINDUNILVR": "Fast Moving Consumer Goods",
  "HINDZINC": "Metals & Mining",
  "HYUNDAI": "Automobile and Auto Components",
  "ICICIBANK": "Financial Services",
  "INDHOTEL": "Consumer Services",
  "INDIGO": "Services",
  "INFY": "Information Technology",
  "IOC": "Oil Gas & Consumable Fuels",
  "IRFC": "Financial Services",
  "ITC": "Fast Moving Consumer Goods",
  "JINDALSTEL": "Metals & Mining",
  "JIOFIN": "Financial Services",
  "JSWSTEEL": "Metals & Mining",
  "KOTAKBANK": "Financial Services",
  "LODHA": "Realty",
  "LT": "Construction",
  "LTM": "Information Technology",
  "M&M": "Automobile and Auto Components",
  "MARUTI": "Automobile and Auto Components",
  "MAXHEALTH": "Healthcare",
  "MAZDOCK": "Capital Goods",
  "MOTHERSON": "Automobile and Auto Components",
  "MUTHOOTFIN": "Financial Services",
  "NESTLEIND": "Fast Moving Consumer Goods",
  "NTPC": "Power",
  "ONGC": "Oil Gas & Consumable Fuels",
  "PFC": "Financial Services",
  "PIDILITIND": "Chemicals",
  "PNB": "Financial Services",
  "POWERGRID": "Power",
  "RECLTD": "Financial Services",
  "RELIANCE": "Oil Gas & Consumable Fuels",
  "SBILIFE": "Financial Services",
  "SBIN": "Financial Services",
  "SHREECEM": "Construction Materials",
  "SHRIRAMFIN": "Financial Services",
  "SIEMENS": "Capital Goods",
  "SOLARINDS": "Chemicals",
  "SUNPHARMA": "Healthcare",
  "TATACAP": "Financial Services",
  "TATACONSUM": "Fast Moving Consumer Goods",
  "TATAPOWER": "Power",
  "TATASTEEL": "Metals & Mining",
  "TCS": "Information Technology",
  "TECHM": "Information Technology",
  "TITAN": "Consumer Durables",
  "TMCV": "Capital Goods",
  "TMPV": "Automobile and Auto Components",
  "TORNTPHARM": "Healthcare",
  "TRENT": "Consumer Services",
  "TVSMOTOR": "Automobile and Auto Components",
  "ULTRACEMCO": "Construction Materials",
  "UNIONBANK": "Financial Services",
  "UNITDSPR": "Fast Moving Consumer Goods",
  "VBL": "Fast Moving Consumer Goods",
  "VEDL": "Metals & Mining",
  "WIPRO": "Information Technology",
  "ZYDUSLIFE": "Healthcare",
};

export const ETF_WHITELIST = [
  "NIFTYBEES", "JUNIORBEES", "BANKBEES", "GOLDBEES", "ITBEES",
] as const;

export const UNIVERSE: ReadonlySet<string> = new Set<string>([...NIFTY100, ...ETF_WHITELIST]);
